// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAefQ6N874zPSGt2D94QdlZzyGPtnU9P2w',
    appId: '1:175435654243:web:1cdaa30d1afe1eb5024456',
    messagingSenderId: '175435654243',
    projectId: 'cashier-app-34caf',
    authDomain: 'cashier-app-34caf.firebaseapp.com',
    storageBucket: 'cashier-app-34caf.appspot.com',
    measurementId: 'G-2E9ZD6T4GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzeOh6c1RU7lOoW4rFGpZHgUMf__Q0RE',
    appId: '1:175435654243:android:3750aabec5a857ac024456',
    messagingSenderId: '175435654243',
    projectId: 'cashier-app-34caf',
    storageBucket: 'cashier-app-34caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjfzYfvrlTc-e8QeuV5399TxxCBBXQb8',
    appId: '1:175435654243:ios:51f15c8a4d70164e024456',
    messagingSenderId: '175435654243',
    projectId: 'cashier-app-34caf',
    storageBucket: 'cashier-app-34caf.appspot.com',
    iosBundleId: 'com.example.cashierApp',
  );
}
